from django.urls import path
from .views import *

urlpatterns = [
    path('', page_1),
    path('page2', page_2),
    path('page3', page_3),
    path('details_1', transactions_details_1),
    path('details_2', transactions_details_2),
    path('details_3', transactions_details_3),
    path('details_4', transactions_details_4),
    path('details_5', transactions_details_5),
    path('details_6', transactions_details_6),
    path('details_7', transactions_details_7),
    path('details_8', transactions_details_8),
    path('details_9', transactions_details_9),
    path('details_10', transactions_details_10),
    path('details_11', transactions_details_11),
    path('details_12', transactions_details_12),
    path('details_13', transactions_details_13),
    path('details_14', transactions_details_14),
    path('details_15', transactions_details_15),
    path('details_16', transactions_details_16),
    path('details_17', transactions_details_17),
    path('details_18', transactions_details_18),
    path('details_19', transactions_details_19),
    path('details_20', transactions_details_20),
    path('details_21', transactions_details_21),
    path('details_22', transactions_details_22),
    path('details_23', transactions_details_23),
    path('details_24', transactions_details_24),
    path('details_25', transactions_details_25),
    path('details_26', transactions_details_26),
    path('details_27', transactions_details_27),
    path('details_28', transactions_details_28),
    path('details_29', transactions_details_29),
    path('details_30', transactions_details_30),
]