# Generated by Django 3.1.4 on 2021-05-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_table',
            name='Name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crm_table',
            name='Number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
